<?php $_enabled = Mage::getStoreConfigFlag('brainsins_recommender_options/brainsins_recommender_general/enabled', Mage::app()->getStore()->getStoreId()); ?>
<?php if ($_enabled):
    $_bskey = Mage::getStoreConfig('brainsins_recommender_options/brainsins_recommender_general/bs_key', Mage::app()->getStore()->getStoreId());
    $_bs_ajax_tracking = Mage::getStoreConfig('brainsins_recommender_options/brainsins_recommender_advanced/ajax_tracking', Mage::app()->getStore()->getStoreId());
    $_bs_custom_script = Mage::getStoreConfig('brainsins_recommender_options/brainsins_recommender_advanced/custom_script', Mage::app()->getStore()->getStoreId());
    $_apiMode = Mage::getStoreConfig('brainsins_recommender_options/brainsins_recommender_advanced/api_mode', Mage::app()->getStore()->getStoreId());
    $_script_path = "/brainsins.js";
    $_custom_script_path = "/$_bskey/$_bskey.js";
    $_url = Mage::getUrl("brainsins/tracking/bdata", array('_secure' => true));

    function bsIsHomePage()
    {
        return Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() . '/' . Mage::app()->getRequest()->getRouteName() == 'index/index/cms';
    }

    function bsIsProductPage()
    {
        return Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() == 'product/view';
    }

    function bsIsCartPage()
    {
        $path=Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName();
        return $path == 'cart/index' || $path== 'checkout_cart/index';
    }

    function bsIsCheckoutPage()
    {
        return Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() == 'onepage/index' ||
        Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() == 'multishipping/addresses';
    }

    function bsIsThankYouPage()
    {
        return Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() == 'onepage/success';
    }

    function bsIsCategoryPage()
    {
        return Mage::app()->getRequest()->getControllerName() . '/' . Mage::app()->getRequest()->getActionName() == 'category/view';
    }

    function bsCurrentProduct()
    {
        return Mage::helper('brainsins_recommender')->productIdForTracking(Mage::registry('current_product'));
    }

    function bsCurrentCategory()
    {
        return Mage::helper('brainsins_recommender')->categoryIdForTracking(Mage::registry('current_category'));
    }

    function bsBuildRecommendationsRequest()
    {
        $recommenders = Array();
        return $recommenders;
    }

    function bsCartInfo($sendWs = false)
    {
        $quote = Mage::getSingleton('checkout/session')->getQuote();
        //$cart["products"] = Mage::helper('brainsins_recommender')->processQuote($quote);
        $cart = Mage::helper('brainsins_recommender')->processQuote($quote);
        return $cart;
    }

    function bsLoginInfo($bdata)
    {
        $bs_register = Mage::getSingleton('core/cookie')->get('brainsins_register');
        $bs_login = Mage::getSingleton('core/cookie')->get('brainsins_login');
        $bs_logout = Mage::getSingleton('core/cookie')->get('brainsins_logout');
        $bs_news = Mage::getSingleton('core/cookie')->get('brainsins_news');

        $email_tracking = Mage::getStoreConfig('brainsins_recommender_options/brainsins_recommender_general/email_tracking', Mage::app()->getStore()->getStoreId());

        if ($bs_register) {
           $customer_id = Mage::getSingleton('core/cookie')->get('brainsins_register');
        } else if ($bs_login) {
           $customer_id = Mage::getSingleton('core/cookie')->get('brainsins_login');
        } else if ($bs_logout) {
           $customer_id = Mage::getSingleton('core/cookie')->get('brainsins_logout');
        }
        $customer = $customer_id ? Mage::getModel('customer/customer')->load($customer_id) : false;
        $subscriber = $customer ? Mage::getModel('newsletter/subscriber')->loadByEmail($customer->getEmail()) : false;
        $subscribed = $subscriber && $subscriber->getId() && $subscriber->getSubscriberStatus() == '1';

        if ($customer && ($bs_register || $bs_login)) {
            $bdata["login"] = "1";
            $bdata["userEmail"] = $customer->getEmail();
            if ($email_tracking == "1") {
                $bdata["userNewsletter"] = $subscribed ? "1" : "0";
            } else if ($email_tracking == "2") {
                $bdata["userNewsletter"] = "1";
            } else {
                $bdata["userNewsletter"] = "0";
            }
        } else if (Mage::getSingleton('core/cookie')->get('bsUl') === "1") {
            $bdata["logout"] = 1;
        }

        return $bdata;


    }

    function bsBuildBdata($doLogin)
    {
        $bdata = Array();
        $bdata["language"] = Mage::app()->getStore()->getCode();
        $bdata["currency"] = Mage::app()->getStore()->getCurrentCurrencyCode();
        $pageType = "other";

        if (bsIsHomePage()) {
            $pageType = "home";
            $bdata["pageType"] = "home";
        }

        if (bsIsCategoryPage()) {
            $pageType = "category";
            $bdata["pageType"] = "category";
            $bdata["categoryId"] = bsCurrentCategory();
        }

        if (bsIsProductPage()) {
            $pageType = "product";
            $bdata["pageType"] = "product";
            $bdata["productId"] = bsCurrentProduct();
        }

        if (bsIsCartPage()) {
            $pageType = "cart";
            $bdata["pageType"] = "cart";
            $bdata["cart"] = bsCartInfo(false);
            //track misc data for order
            $session = Mage::getSingleton('checkout/session');
            if($session->getData("brainsins_qhash")){
                $bdata["cartMisc"] =array(
                    "quoteId"=>$session->getQuoteId(),
                    "brainsins_qhash"=>$session->getData("brainsins_qhash")
                    );
            }           
        }

        if (bsIsCheckoutPage()) {
            $pageType = "checkout";
            $bdata["pageType"] = "checkout";
        }

        if (bsIsThankYouPage()) {
            $pageType = "thankYou";
            $bdata["pageType"] = "thankYou";
            $orderId = Mage::getSingleton('checkout/session')->getLastOrderId();
            $order = Mage::getModel('sales/order')->load($orderId);

            $total = Mage::helper('brainsins_recommender')->getTotalAmount($order);
            if ($total) {
                $bdata["totalAmount"] = $total;
                if(is_callable(array($order,"getIncrementId"))){
                    $bdata["idPurchase"] = $order->getIncrementId();
                }else{
                    $bdata["message"]="getIncrementId not found";
                    error_log("[BrainSINS] getIncrementId not found");
                }
            }
        }

        $recommenders = Mage::helper('brainsins_recommender')->getPageRecommenders($pageType);
        if ($recommenders && count($recommenders > 0)) {
            $bdata["recommenders"] = $recommenders;
        }

        if ($doLogin) {
            $bdata = bsLoginInfo($bdata);
        }

        return $bdata;
    }


    ?>
    <!-- BrainSINS Code Starts -->
    <script type='text/javascript'>

        <?php

            $_lang = Mage::app()->getStore()->getCode();
            $currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

            if ($_bs_ajax_tracking) {
                $bdata = bsBuildBdata(false);
            } else {
                $bdata = bsBuildBdata(true);
                $bdata["trackingMode"] = "standard";
            }

            foreach ($bdata as $key => $value) {
                 echo "BrainSINSData.$key = " . json_encode($bdata[$key]) . ";" . PHP_EOL;
            }

        ?>

        <?php if ($_bs_ajax_tracking):?>

            <?php if ($_bs_custom_script):?>
            var bs_custom_script = true;
            <?php endif;?>

            var bdata_controller_url = "<?php echo $_url?>";
            bdata_controller_url += "rnd/" + new Date().getTime() + "/";
            //bdata_controller_url += "bdata/" + encodeURIComponent(JSON.stringify(BrainSINSData));
            bdata_controller_url = bdata_controller_url.replace("https:", "").replace("http:", "");

            new Ajax.Request(bdata_controller_url, {
                method: "get",
                onSuccess: function (transport) {
                    var newBdata = transport.responseJSON;
                    if (newBdata) {
                        BrainSINSData.login = newBdata.login;
                        BrainSINSData.userNewsletter = newBdata.userNewsletter;
                        BrainSINSData.userEmail = newBdata.userEmail;
                        BrainSINSData.logout = newBdata.logout;
                        BrainSINSData.trackingMode = "ajax";
                        if (typeof showBsInfo == "function") {
                            setTimeout(function () {
                                showBsInfo();
                            }, 1000)
                        }
                    }

                    var domain = "." + window.location.hostname;
                    bsUnsetCookie("brainsins_login", domain);
                    bsUnsetCookie("brainsins_news", domain);
                    bsUnsetCookie("brainsins_register", domain);
                    bsUnsetCookie("brainsins_logout", domain);

                    loadBrainSINSScript('<?php echo $_script_path ?>');
                    <?php if ($_bs_custom_script):?>
                        loadBrainSINSScript('<?php echo $_custom_script_path ?>');
                    <?php endif;?>

                }
            });
        <?php endif;?>
    </script>
    <!-- BrainSINS Code Ends -->
<?php endif; ?>
